name       : efl
version    : 1.25.1
release    : 19
source     :
    - http://download.enlightenment.org/rel/libs/efl/efl-1.25.1.tar.xz : 351ca0211ca000234527a503585f039f985607ec9439e34b49d8b8bbf35a7e6b
license    :
    - BSD-2-Clause
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
    - Zlib
component  : desktop.library
summary    : Enlightenment Foundation Libraries
description: |
    EFL is a collection of libraries for handling many common tasks a developer may have such as data structures, communication, rendering, widgets and more.
optimize   :
    - lto
    - speed
libsplit   : no
patterns   :
    - devel :
        - /usr/bin
        - /usr/share/applications
        - /usr/share/ecore*
        - /usr/share/elementary/objects
        - /usr/share/elementary/test*
        - /usr/share/embryo
        - /usr/share/emotion
        - /usr/share/eolian
        - /usr/share/gdb
    - main :
        - /usr/bin/efreetd
        - /usr/bin/eeze*
        - /usr/bin/elementary_config
        - /usr/bin/elementary_quicklaunch
        - /usr/bin/elementary_run
        - /usr/bin/exactness*
        - /usr/bin/ethumb*
        - /usr/share/applications/elementary_config.desktop
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(avahi-core)
    - pkgconfig(bullet)
    - pkgconfig(check)
    - pkgconfig(fribidi)
    - pkgconfig(gbm)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(ibus-1.0)
    - pkgconfig(libcurl)
    - pkgconfig(libinput)
    - pkgconfig(liblz4)
    - pkgconfig(libopenjp2)
    - pkgconfig(libpulse)
    - pkgconfig(libraw)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libspectre)
    - pkgconfig(libtiff-4)
    - pkgconfig(libturbojpeg)
    - pkgconfig(libunwind)
    - pkgconfig(libwebp)
    - pkgconfig(luajit)
    - pkgconfig(poppler)
    - pkgconfig(sdl2)
    - pkgconfig(sndfile)
    - pkgconfig(xcomposite)
    - pkgconfig(xcursor)
    - pkgconfig(xdamage)
    - pkgconfig(xinerama)
    - pkgconfig(xkbcommon)
    - pkgconfig(xpm)
    - pkgconfig(xpresent)
    - pkgconfig(xrandr)
    - pkgconfig(xscrnsaver)
    - pkgconfig(xtst)
    - gettext-devel
    - giflib-devel
    - libiconv-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Remove-UID-check-since-it-causes-FTBFS-in-build.patch
    %meson_configure \
        -Davahi=true \
        -Dbuffer=true \
        -Dbuild-id='solus' \
        -Dbuild-tests=false \
        -Decore-imf-loaders-disabler='scim' \
        -Dglib=true \
        -Dopengl='full' \
        -Dpixman=true \
        -Dsdl=true
build      : |
    %ninja_build
install    : |
    %ninja_install
