name       : efl
version    : 1.20.6
release    : 9
source     :
    - https://download.enlightenment.org/rel/libs/efl/efl-1.20.6.tar.xz : 56c67ea77435753a4f324a0a13488ba58f4ed7eb35a97c1a354fdc79c39a32c1
license    :
    - BSD-2-Clause
    - GPL-2.0
    - LGPL-2.1
    - Zlib
component  : desktop.library
summary    : Enlightenment Foundation Libraries
description: |
    EFL is a collection of libraries for handling many common tasks a
    developer may have such as data structures, communication, rendering,
    widgets and more.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(avahi-client)
    - pkgconfig(bullet)
    - pkgconfig(gl)
    - pkgconfig(gstreamer-base-1.0)
    - pkgconfig(gstreamer-plugins-base-1.0)
    - pkgconfig(gstreamer-audio-1.0)
    - pkgconfig(gstreamer-video-1.0)
    - pkgconfig(gstreamer-tag-1.0)
    - pkgconfig(gstreamer-pbutils-1.0)
    - pkgconfig(harfbuzz)
    - pkgconfig(ibus-1.0)
    - pkgconfig(fribidi)
    - pkgconfig(luajit)
    - pkgconfig(libcurl)
    - pkgconfig(libudev)
    - pkgconfig(libraw)
    - pkgconfig(librsvg-2.0)
    - pkgconfig(libdrm)
    - pkgconfig(libinput)
    - pkgconfig(liblz4)
    - pkgconfig(libpulse)
    - pkgconfig(libspectre)
    - pkgconfig(libtiff-4)
    - pkgconfig(libturbojpeg)
    - pkgconfig(libpng)
    - pkgconfig(mount)
    - pkgconfig(sndfile)
    - pkgconfig(freetype2)
    - pkgconfig(fontconfig)
    - pkgconfig(openssl)
    - pkgconfig(poppler)
    - pkgconfig(zlib)
    - pkgconfig(xdamage)
    - pkgconfig(xext)
    - pkgconfig(xfixes)
    - pkgconfig(xtst)
    - pkgconfig(xcb)
    - pkgconfig(xcb-shape)
    - pkgconfig(xcomposite)
    - pkgconfig(xcursor)
    - pkgconfig(xinerama)
    - pkgconfig(xkbcommon)
    - pkgconfig(xrandr)
    - pkgconfig(xpresent)
    - pkgconfig(xscrnsaver)
    - pkgconfig(wayland-protocols)
    - pkgconfig(wayland-scanner)
    - pkgconfig(libwebp)
    - pkgconfig(tslib)
    - giflib-devel
    - check
patterns   :
    - devel :
        - /usr/bin
        - /usr/share/eolian
        - /usr/share/gdb
        - /usr/share/applications
    - main :
        - /usr/bin/eeze*
        - /usr/bin/efreetd
        - /usr/bin/ethumbd*
        - /usr/bin/elementary_quicklaunch
        - /usr/bin/elementary_run
setup      : |
    # TODO: --enable-gesture \
    # TODO: --enable-always-build-examples
    %configure --enable-xinput22 \
               --enable-xpresent \
               --enable-harfbuzz \
               --with-opengl=full \
               --enable-fb \
               --enable-liblz4 \
               --enable-wayland \
               --enable-elput \
               --enable-drm \
               --disable-gesture \
               --enable-multisense \
               --enable-image-loader-webp \
               --enable-image-loader-jpeg \
               --disable-always-build-examples \
               --with-id=solus \
               --with-profile=release
build      : |
    %make
install    : |
    %make_install
